const data =[
    {
        productName:"Apple",
        pricePerQuantityGross:100,
        VAT:25,
        pricePerQuantityNet:75,
        totalStocks:10,
        image:"url"
    },
    {
            productName:"Mango",
            pricePerQuantityGross:100,
            VAT:35,
            pricePerQuantityNet:75,
            totalStocks:10,
            image:"url"
    },
    {
        productName:"Banana",
        pricePerQuantityGross:100,
        VAT:45,
        pricePerQuantityNet:75,
        totalStocks:10,
        image:"url"
    },
    {
        productName:"Orange",
        pricePerQuantityGross:100,
        VAT:55,
        pricePerQuantityNet:75,
        totalStocks:10,
        image:"url"
    }
]
export default data